# Rose Pine foot config
include=~/.config/foot/rose-pine.conf

[main]
font=Iosevka Nerd Font:size=11
term=xterm-256color
pad=8x8
selection-target=clipboard

[scrollback]
lines=10000
multiplier=3.0
indicator-position=relative

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[bell]
visual=no
urgent=no
notify=no
